### ISSUE TITLE
Random form order

### ISSUE THREAD

**Issue by mdevlamynck** [bmispelon/django-multiform#9]
I used MultiModelForm to combine django's UserCreationForm and the ModelForm of my Profile model (same use case as in the doc).

Each time I restart the server, the order in which the forms are rendered is random. Sometimes the UserCreationForm is rendered first then the other, sometimes its the other way around.

**Comment by MarkusH** [comment]
Use a `OrderedDict`:

```python
from collections import OrderedDict

class FooBarForm(MultiForm):
    base_forms = OrderedDict([
        ('foo', FooForm),
        ('bar', BarForm),
    ])
```

**Comment by mdevlamynck** [comment]
Nice thanks ! It would be nice to update the doc though.

**Comment by MarkusH** [comment]
Just realized when writing a doc patch: you can even get off without an `OrderedDict` and just use a list of 2-tuples.
